# Generated by Django 3.0 on 2020-02-05 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tba_app', '0004_registration_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='expirydate',
            field=models.DateField(blank=True, max_length=20, null=True),
        ),
    ]
